#!/bin/bash
echo ""
echo "To view all the GVA process logs run this script:"
echo "    ~/validation-tools/view-gva-logs-all.sh  "
echo ""
echo ""
echo "To view the logs for a single GVA process, use this script:"
echo "    ~/validation-tools/view-gva-process.sh  "
echo ""
echo ""
